import { baseURL } from "./apiEndPoints"
export const GET_URL = baseURL + "/api/configuration/config-get"
export const PUT_URL = baseURL +  "/api/config-update"
export const POST_URL = baseURL +  "/api/config-save"
export const FEATURE_URL = "https://func-price-wrapperoverappconfig-test-02.azurewebsites.net/api/features-get?"
